FORMATTERS_DISABLE_ERRORS: false

# Python
PRE_COMMANDS:
  - command: >-
      python -m pip install --upgrade
      --target .megalinter-python-deps
      -r docs/source/requirements.txt &&
      export PYTHONPATH="$PWD/.megalinter-python-deps"
    cwd: workspace
    run_before_linters: true
    continue_if_failed: false
    output_variables:
      - PYTHONPATH
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_ARGUMENTS: "--errors-only"

# bash-exec
BASH_EXEC_FILE_EXTENSIONS: [".sh", ".dash", ".ksh"]

# jscpd
COPYPASTE_JSCPD_ARGUMENTS: "--threshold 10"

# shfmt
BASH_SHFMT_ARGUMENTS: "--indent 2 -case-indent"

# trivy
REPOSITORY_TRIVY_ARGUMENTS: "--ignorefile ./.trivyignore.yaml"

# zizmor
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
